# Generated by Django 6.1 on 2026-08-21 11:21

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('target_role', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetRoleCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
    ]
