# Generated by Django 6.1 on 2026-08-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='keyword_gap',
            field=models.JSONField(default=list),
        ),
    ]
